### ISSUE TITLE
Letter count miscount led failed to post on Twitter

### ISSUE THREAD

**Issue by 0xtaipoian** [depub-team/depub.space#117]
Reference:
https://depub.space/gVULj-iyFr-kMnlsBUljWx-QY-ZvXWLkmtUel_TYOZg/1

**Comment by RicardDeLa** [comment]
https://developer.twitter.com/en/docs/counting-characters
Here listed the logic of twitter character count, the above failed post is because twiiter parse "depub.space"  as link and count as 23 char

According to the doc, twitter suggest to use their library
https://github.com/twitter/twitter-text/tree/master/js

fixed in commit https://github.com/depub-team/depub.space/commit/1177721a1411b3ae8e1ddbfdd99bb112018b593c
